<a href="https://colab.research.google.com/github/Vishwaak/Time-for-Machine/blob/master/Baisc_Tensors_actions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
def activation(x):
  
  return 1/(1+torch.exp(-x))

In [16]:
activation(features)

TypeError: ignored

In [0]:
torch.manual_seed(7)

features  = torch.randn((1,5))
weights = torch.rand_like(features)

bias = torch.randn((1,1))


In [0]:
mine = torch.mul(features,weights)
#mul function helps in mutiply tensors of different sizes 

In [0]:
wine =  mine.sum() + bias

In [20]:
y =(activation(wine))
print(y)

tensor([[0.6140]])


In [0]:
#simple algebric solution
y = activation((features * weights).sum() + bias)

In [23]:
print(y)

tensor([[0.6140]])


In [25]:
y= activation(torch.mm(features, weights.view(5,1))+  bias)
print(y)

tensor([[0.6140]])


In [30]:
#sum of multiple layer network
torch.manual_seed(7)
features =torch.randn((1,3))
n_input = features.shape[1]
n_hidden = 2
n_output = 1  
W1 = torch.randn(n_input , n_hidden)
W2 = torch.randn(n_hidden , n_output)

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1 ,n_output))

h = activation(torch.mm(features , W1) + B1)
output  = activation(torch.mm(h , W2) + B2)

print(output)

tensor([[0.3171]])
